baseURL = "https://blog-tawny-kappa.vercel.app/"
languageCode = "en-us"
title = "Douglas Delabrida"
theme = "hugo-theme-codex"

[params]
  showPageTitleInTOC = true
  linkedin = "https://twitter.com/dougdelabrida"
  github = "https://github.com/dougdelabrida"
  # ...

  iconOrder = ["LinkedIn", "GitHub"]

[[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/"
[[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"